/* The v1 generator core — answers → a no-op-but-green package. Pure of any
 * prompt UI so the rot-test and the CLI both call it. */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { nameForms, validateName, copyTree, SUBSTRATES_DIR } from "./core.mjs";
import { QUESTIONS, validateAnswers } from "./questions.mjs";
import { TEMPLATES } from "./templates.mjs";

// Generate the package. The roster is glob-discovered from
// `src/substrates/<name>/index.ts` (src/app/substrates.ts), so creating the
// directory is all it takes to register — there is no registry file to patch.
export function generate(name, answers) {
  const nameErr = validateName(name);
  if (nameErr) throw new Error(nameErr);
  const ansErr = validateAnswers(answers);
  if (ansErr) throw new Error(ansErr);

  const forms = nameForms(name);
  const dest = join(SUBSTRATES_DIR, name);
  copyTree(dest, { forms, answers }, TEMPLATES);
  writeFileSync(join(dest, "DESIGN.md"), designDoc(forms, answers));
  return { dest, forms };
}

// The package's design record — the six answers, captured. Doubles as the
// seed for the substrate's own published doc.
function designDoc(forms, answers) {
  const rows = QUESTIONS.map((q) => {
    const opt = q.options.find((o) => o.value === answers[q.id]);
    return `| ${q.docQ} | ${q.title} | **${opt ? opt.label : answers[q.id]}** |`;
  }).join("\n");

  return `# ${forms.title} — design record

Generated by \`new-substrate\`. The six design questions this substrate was
scaffolded against (see \`docs/guide.md\`):

| Q | Question | Answer |
|---|----------|--------|
${rows}

## What the scaffold gave you

A no-op-but-green package: it compiles, is auto-discovered by the roster,
mounts, and ticks a no-op. The kit imports, \`Inputs\` shape, storage alloc,
commit predicate, and feature flags are pre-toggled by the answers above.

## What's left (the thinking, not the busywork)

- **engine/** — the real tick (physics), state fields, channels, commit payload.
- **lens/** — the real render + input handling.
- **puzzles/** — replace the placeholder level.
- Trim the template boilerplate carried in comments.

Verify as you go: \`npx tsc --noEmit && npx vitest run\`, then open
\`?substrate=${forms.kebab}\`.
`;
}
