#!/usr/bin/env node
/* export-embed — bundle a substrate into a single self-contained, post-ready
 * HTML file (and a reusable IIFE JS bundle), no React, no app chrome.
 *
 * Usage:
 *   npm run export -- <substrate-id> [options]
 *
 * Options (all "setupable" — see EmbedConfig in src/embed/mount-substrate.ts):
 *   --puzzle=<id>        puzzle to load (default: substrate's default)
 *   --lens=<id>          lens to mount (default: substrate's default)
 *   --seed=<n>           RNG seed
 *   --speed=<id>         speed preset id (one of the lens's speeds)
 *   --no-autoplay        mount paused
 *   --loop               self-loop at the end of the run (substrates honouring it)
 *   --touch-action=<v>   touch-gesture policy: none (full capture) | pan-y
 *                          (vertical scroll passes through) | … (default: page scrolls)
 *   --precomputed=<file> bake a JSON blob as a default `config.precomputed`
 *   --set <name>=<val>   set a tunable (repeatable); val coerces bool/number
 *   --title=<text>       page <title> (default: the substrate name)
 *   --js-only            emit only the .js bundle, skip the standalone .html
 *   --skip-typecheck     skip the tsc --noEmit gate
 *   --skip-guest         don't (re)build the SDK guest page (dist-embed/embed.html)
 *
 * Output: dist-embed/<id>.html  +  dist-embed/<id>-embed.js  +  dist-embed/embed.html
 *         (the last is the spec/25 SDK guest runtime, shared by all embeds)
 *
 * Substrates with a bespoke react-less entry (blockoide) are built from it;
 * everything else uses the generic registry-free `mountSubstrate`. A substrate
 * only exports React-free once its lenses use the LensHost seam (no
 * `@/app/store` import) — until then the bundle still works but pulls React.
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIST = path.join(ROOT, "dist-embed");
const GEN_DIR = path.join(ROOT, "src", "embed", ".generated");

// Substrates with a hand-written react-less embed entry (different mount API).
const BESPOKE = {
  blockoide: { entry: "src/embed/blockoide.ts", global: "Blockoide", mountFn: "mountBlockoide" },
};

function coerce(v) {
  if (v === "true") return true;
  if (v === "false") return false;
  if (v !== "" && !Number.isNaN(Number(v))) return Number(v);
  return v;
}

function parseArgs(argv) {
  const positional = [];
  const flags = {};
  const sets = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--set") {
      sets.push(argv[++i] ?? "");
    } else if (a.startsWith("--")) {
      const eq = a.indexOf("=");
      if (eq === -1) flags[a.slice(2)] = true;
      else flags[a.slice(2, eq)] = a.slice(eq + 1);
    } else {
      positional.push(a);
    }
  }
  const tunables = {};
  for (const s of sets) {
    const eq = s.indexOf("=");
    if (eq === -1) continue;
    tunables[s.slice(0, eq)] = coerce(s.slice(eq + 1));
  }
  return { positional, flags, tunables };
}

function listFiles(dir) {
  return fs.existsSync(dir) ? new Set(fs.readdirSync(dir)) : new Set();
}

function writeGenericEntry(id, precomputed) {
  fs.mkdirSync(GEN_DIR, { recursive: true });
  const file = path.join(GEN_DIR, `${id}.ts`);
  // When a precompiled blob is baked, inline it and merge it UNDER the page's
  // mount opts (so the page can still override it), then pass to mountSubstrate.
  const preLine = precomputed
    ? `const precomputed = ${JSON.stringify(precomputed)} as unknown;\n`
    : "";
  const opt = precomputed
    ? "{ precomputed, ...((opts as Record<string, unknown> | undefined) ?? {}) }"
    : "opts";
  fs.writeFileSync(
    file,
    `/* AUTO-GENERATED by scripts/export-embed.mjs — do not edit. */
import { mountSubstrate, type SubstrateModule } from "@/embed/mount-substrate";
import * as Sub from "@/substrates/${id}";
${preLine}
(window as unknown as { CosoEmbed?: unknown }).CosoEmbed = {
  mount: (target: HTMLElement | string, opts?: unknown) =>
    mountSubstrate(target, Sub as unknown as SubstrateModule, ${opt} as never),
};
`,
  );
  return path.relative(ROOT, file);
}

function buildEmbedConfig(flags, tunables, bespoke) {
  if (bespoke === "blockoide") {
    // BlockoideEmbedOptions: puzzle is a JSON object, plus autopilot.
    const cfg = {};
    if (flags.puzzle) {
      const p = path.join(ROOT, "src", "substrates", "blockoide", "puzzles", `${flags.puzzle}.json`);
      if (fs.existsSync(p)) cfg.puzzle = JSON.parse(fs.readFileSync(p, "utf8"));
    }
    if (flags.seed !== undefined) cfg.seed = Number(flags.seed);
    if (flags["no-autoplay"]) cfg.autoplay = false;
    if (flags["no-autopilot"]) cfg.autopilot = false;
    if (Object.keys(tunables).length) cfg.tunables = tunables;
    return cfg;
  }
  // Generic EmbedConfig.
  const cfg = {};
  if (flags.puzzle) cfg.puzzle = flags.puzzle;
  if (flags.lens) cfg.lens = flags.lens;
  if (flags.seed !== undefined) cfg.seed = Number(flags.seed);
  if (flags.speed) cfg.speed = flags.speed;
  if (flags["no-autoplay"]) cfg.autoplay = false;
  if (flags.loop) cfg.loop = true;
  if (flags["touch-action"]) cfg.touchAction = flags["touch-action"];
  if (Object.keys(tunables).length) cfg.tunables = tunables;
  return cfg;
}

function standaloneHtml({ title, js, css, global, mountFn, config }) {
  const cfgJson = JSON.stringify(config);
  return `<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${title}</title>
<style>
  html, body { margin: 0; height: 100%; background: #0a0a0a; }
  #app { position: fixed; inset: 0; }
${css}
</style>
</head>
<body>
<div id="app"></div>
<script>${js}</script>
<script>
  window.${global}.${mountFn}(document.getElementById("app"), ${cfgJson});
</script>
</body>
</html>
`;
}

// The generic guest page (spec/25) — substrate-agnostic. Built once from the SDK
// guest entry and shared by every embed the Conductor mounts (it loads the actual
// <id>-embed.js bundle by URL param at runtime). Emitted on every export so it
// tracks the SDK; `--skip-guest` opts out.
function guestHtml(js, css) {
  return `<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>El Coso embed</title>
<style>
  html, body { margin: 0; height: 100%; background: #0a0a0a; overflow: hidden; }
  #app { position: fixed; inset: 0; }
${css}
</style>
</head>
<body>
<div id="app"></div>
<script>${js}</script>
</body>
</html>
`;
}

function emitGuestPage() {
  const file = "embed-runtime.js";
  console.log("• building embed guest runtime (embed.html)…");
  const before = listFiles(DIST);
  execFileSync("npx", ["vite", "build", "--config", "vite.embed.config.ts"], {
    cwd: ROOT,
    stdio: "inherit",
    env: {
      ...process.env,
      COSO_EMBED_ENTRY: "src/embed/sdk/guest-entry.ts",
      COSO_EMBED_NAME: "CosoEmbedGuest",
      COSO_EMBED_FILE: file,
    },
  });
  const js = fs.readFileSync(path.join(DIST, file), "utf8");
  let css = "";
  for (const f of listFiles(DIST)) {
    if (f.endsWith(".css") && !before.has(f)) {
      css += fs.readFileSync(path.join(DIST, f), "utf8");
      fs.rmSync(path.join(DIST, f));
    }
  }
  fs.rmSync(path.join(DIST, file)); // inline-only — keep dist-embed single-file
  const html = guestHtml(js, css);
  fs.writeFileSync(path.join(DIST, "embed.html"), html);
  console.log(`  → dist-embed/embed.html (${(html.length / 1024).toFixed(1)} KB, self-contained)`);
}

function main() {
  const { positional, flags, tunables } = parseArgs(process.argv.slice(2));
  const id = positional[0];
  if (!id) {
    console.error("usage: npm run export -- <substrate-id> [options]");
    console.error("       see scripts/export-embed.mjs for options");
    process.exit(1);
  }

  const bespoke = BESPOKE[id];
  let precomputed;
  if (flags.precomputed) {
    precomputed = JSON.parse(fs.readFileSync(path.resolve(ROOT, flags.precomputed), "utf8"));
  }
  const entry = bespoke ? bespoke.entry : writeGenericEntry(id, precomputed);
  const global = bespoke ? bespoke.global : "CosoEmbed";
  const mountFn = bespoke ? bespoke.mountFn : "mount";
  const jsFile = `${id}-embed.js`;

  if (!flags["skip-typecheck"]) {
    console.log("• typecheck (tsc --noEmit)…");
    execFileSync("npx", ["tsc", "--noEmit"], { cwd: ROOT, stdio: "inherit" });
  }

  // The SDK guest page (spec/25) — substrate-agnostic, built once per run.
  if (!flags["skip-guest"]) emitGuestPage();

  const before = listFiles(DIST);
  console.log(`• building ${id} embed (entry: ${entry})…`);
  execFileSync("npx", ["vite", "build", "--config", "vite.embed.config.ts"], {
    cwd: ROOT,
    stdio: "inherit",
    env: {
      ...process.env,
      COSO_EMBED_ENTRY: entry,
      COSO_EMBED_NAME: global,
      COSO_EMBED_FILE: jsFile,
    },
  });

  const js = fs.readFileSync(path.join(DIST, jsFile), "utf8");

  // Any NEW .css file in dist-embed is this build's extracted CSS — inline it
  // into the HTML and remove the orphan so the export stays single-file.
  let css = "";
  for (const f of listFiles(DIST)) {
    if (f.endsWith(".css") && !before.has(f)) {
      css += fs.readFileSync(path.join(DIST, f), "utf8");
      fs.rmSync(path.join(DIST, f));
    }
  }

  console.log(`  → dist-embed/${jsFile} (${(js.length / 1024).toFixed(1)} KB)`);

  if (flags["js-only"]) return;

  const title = flags.title ?? `${id} — El Coso`;
  const config = buildEmbedConfig(flags, tunables, bespoke ? id : undefined);
  const html = standaloneHtml({ title, js, css, global, mountFn, config });
  const htmlPath = path.join(DIST, `${id}.html`);
  fs.writeFileSync(htmlPath, html);
  console.log(`  → dist-embed/${id}.html (${(html.length / 1024).toFixed(1)} KB, self-contained)`);
}

main();
